#+TITLE: 拜占庭将军问题
#+AUTHOR: PugnaHAN
#+EMAIL: justin_victory@hotmail.com
#+STARTUP: indent
#+DATE: <2016-12-03 周六>
#+OPTIONS: toc:nil

* 前言
在看拜占庭问题之前，我们要想想为什么我们需要研究这个问题。首先，我们先回顾下比特币区块的生成过程：所有的矿工同时计算哈希值，当获取到符合条件的哈希时通知其他矿工，其他矿工验证，若成功则接受且在刚生成区块的条件下进行下一次的哈希计算。仔细观察我们会发现，所有的矿工其实彼此是相互孤立的，但是为了让区块链正常增长有必要使其行动一致。而该问题恰恰是拜占庭将军问题需要解决的。因此，在研究区块链的共识算法之前，我们有必要先认识下什么叫做拜占庭将军问题。
** TODO Add image for generating a block
DEADLINE: <2016-12-05 周一>

* 概述
根据[[http://duanple.blog.163.com/blog/static/7097176720112643946178/][这篇译文]]， 拜占庭将军问题其实是来源于中国将军问题（两军问题），其描述大概是：有两只军队要进攻一个国家，但是只有在同时进攻才能成功，因此其行动必须获取一致性。但是，问题在于他们的通讯方式只有信使，且信使可能会被截杀而无法到达，那么如何才能保证行动一致呢？不过Lamport扩展并修改了这个问题：指挥一组将军来围困拜占庭帝国，不过拜占庭帝国非常强大，必须要要有半数以上（如果是10支军队就是至少10/2 + 1 = 6支）军队同时进攻才能够攻破。不过两只军队不能驻扎在一起（我们可以理解为拜占庭帝国有地利，导致军队只能分散驻扎），且只能通过信使通信（信使一定能够到达且传递正确的信息）。除此之外，将军中存在叛徒，其可能会不进攻或者发布错误的消息。那么如何才能保证行动的一致性呢？其实认真想想，对于我们中国人来说，用春秋战国时期的例子更好理解。齐楚燕赵韩魏秦，我们认为秦国是拜占庭帝国，而其他国家是进攻的将军们。那么这个问题便变成了六国联军怎么才能行动一致的问题。
** 两军问题
我们回过头来思考下两军问题（虽然是拜占庭将军问题的来源，不过二者解决的问题不同），我们称两军分别为A和B。那么整个通信过程便是：A先传递一个消息给B说明天早上五点攻打，但是由于无法确认B是否收到消息，A需要B的一个回执来保证。假设B收到消息然后发送回执给A，但是B又无法确认A是否收到回执而要求A回复一个回执。由于通信信道的不稳定性导致该循环会持续下去。因此，两军问题根本上是要求建立一个可靠安全的连接的问题，因为只要可以保证通信信使一定能够到达对方，那么其实只需要通信一次就够了。但是，并不存在这一通信渠道，因此只能通过多次握手来尽可能降低通信失效的概率，比如TCP链接。（这是我自己的推断，如果错了请指出！）
** 两军问题 vs 拜占庭将军问题 
虽然二者都是要取得行动一致性，不过两军问题在于建立可靠连接，而拜占庭将军问题则在于在有叛徒的前提下依然使得系统能够行动一致，而非建立可靠通信，因为我们认为通信是可靠无误的。拜占庭将军问题最关心的是 *一致性* 解决，要求节点的行动要一致。不过，一致地行动并非代表最优方案，而是保证系统能有预测的运行下去。举个例子来说，比如战国时期，如果站在六国的立场上，最优地行动策略（单纯以总体军事力量来考虑）应该是一起灭了秦国，但是行动的 _一致性_ 却可能出现一起进攻、一起撤退等行为。不过最优策略需要就事论事，我们无法确保一致行动的结果是最优的。总而言之，两军问题 *研究建立可靠的通信方式* ；而拜占庭将军问题研究行动的 *一致性* 。

* 拜占庭将军问题
** 问题实质
根据上面的内容，我们可以很容易推断出其问题实质在于如何使得节点达成 *共识* 。其涉及的问题主要是在有叛徒将军存在的情况下，采用什么策略能够保证将军能达成步调一致以及在什么情况下才能保证步调一致。对于前一个问题，即达成一致行动的方式，很好理解，大致可以认为是所有的将军的行动都必须遵从某些协议，如少数服从多数策略。对于第二个问题，即什么情况下步调才有可能达成一致，我们可以认为如果在叛徒将军数在多少以下才能保证一致性有可能达成（过多的叛徒将军会导致消息传递的无法预测）。

虽然我们在上文提到过 *最优* 是无法确定的，不过，在考虑拜占庭将军问题的时候需要保证行动的可预测性，因此节点的行动需要统一的规则。在拜占庭将军中，由于有忠诚将军和叛徒将军之分，我们要求节点行动的”正确性“就是要求忠诚将军的行动不能被叛徒所误导，保证其行动时都遵从自身的意志。

由此可知，拜占庭将军问题便可以归纳成： _如何才能保证忠诚将军都正确传递自己的思想并最后行动一致_ 。此时问题可能还有点抽象，不过我们再反过头来看拜占庭将军这个故事就很好理解了：
1. 军队都是分散的，只能通过信使传递消息；
2. 军队的领导者——将军都会根据目前的情况给出其观点，比如该进攻还是该撤退。忠诚将军给出的观点应该是符合团队利益的，而叛徒将军的观点则无法预料。
在无法预料谁是叛徒以及叛徒数目的情况下，采用什么办法才能仅仅依靠所受到的信息来保证行动的 *一致性* 与 *正确性* 。 这便是这个问题的本质。

** 判定一致性与正确性的条件
我们思考一下，倘若你是将军，你在判断完战况做出评价之后，会如何传递消息？很明显，如果你是一个忠诚的将军，你肯定会把仔细的想法通过信使传递给其他将军，切他们收到的消息都是一致的；不过，如果你是叛徒的话，会传递不同的消息来影响其他将军的判断。我们用\(v_i\)来作为第\(i\)个将军传递的消息，这样的话最终的消息集就是\((v_{1}, v_{2}, \dots, v_{n-1}, v_{n})\)。不过，这里值得一提的是，假设第\(k\)个将军是叛徒的话，那么每个将军收到的\(v_k\)很有可能是不同的。因此，收到的最终消息集在存在叛徒的情况应该不尽相同。不过，由于所有的将军都需要基于最终消息集和同一行动准则来确定最后行动，因此，如何才能判定最后行动时一致与正确的呢？
- *一致性*
  条件1： 每一个忠诚的将军必须得到相同的\((v_1, v_2, \dots , v_n)\)指令向量或者指令集合。 不过由于存在叛徒，而其发送给别的将军的值可能是不同的，因此，忠诚将军需要将所有值修改成相同的值。不过，仅仅是这样的话，无法判定正确性，因为忠诚将军的观点也可能被修改。这时候就需要正确性的条件了。

- *正确性*
  条件2： 若\(i\)将军是忠诚的，其他忠诚的将军必须以他送出的值作为\(v_i\)。似乎有些拗口，其意思是忠诚将军的值没有其他接收到信息的忠诚将军被修改，保留了他们的观点。联系条件1，我们可以简单得出只有叛徒的观点可能被修改。

稍微转换下条件1，条件1'：我们也可以将其改写成无论\(i\)将军是忠诚还是叛徒，忠诚将军都使用相同的\(v_i\)。如果我们能得出条件1或1'与条件2，那么我们就可以推断拜占庭将军问题的正确性与一致性得到了解决（充分条件，非必要条件）。

在基于条件1'和条件2的基础上，我们可以将问题稍作转化，即：\(i\)将军如何让其他将军接受他的观点且不修改。因此，该问题可以转化为司令-副官模型来简化问题，即一个司令把观点送递给其他副官，保证：
1. 忠诚副官遵守同一命令，保证一致性；
2. 若司令是忠诚的，则副官遵守他所发出的命令，保证正确性。
以上两条分别保证了条件1'和条件2，只不过由于问题模型的变化，使得问题更加直观和明了。而且，对于司令-副官模型，如果所有节点都达成一致了，那么一致性的条件便满足了。但是，如果有节点存在异议，则该节点可以作为新的司令来发起新一轮的协商一致。
